### ISSUE TITLE
non static field BluePayClient.SaleAsync

### ISSUE THREAD

**Issue by Zealouseappex** [syunakh/BluePay#1]
Using the NuGet package for a webform C# project I am getting an:

`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0120	An object reference is required for the non-static field, method, or property 'BluePayClient.SaleAsync(SaleRequest)'	BluPay	D:\Projects\BluPay\BluPay\Default.aspx.cs	55	Active `

Here is the complete code:

 ```
public async Task SaleTest()
        {
            const decimal amount = 101;
            var response = await SaleAsync(amount);

            Debug.WriteLine(response.Status == BluePayPayments.Enums.StatusResponse.Approved);
        }
        private Task<BaseResponse> SaleAsync(decimal amount, BluePayPayments.Enums.Version version = BluePayPayments.Enums.Version.Version1)
        {
            var request = new SaleCreditCardRequest
            {
                CardNumber = "4111111111111111",
                CVV = "123",
                MonthExpiration = 12,
                YearExpiration = DateTime.Now.AddYears(1).Year,
                Amount = amount,
                CustomerInfo = new CustomerInfo
                {
                    FirstName = "Name",
                    LastName = "LastName"
                },
                Version = version
            };

            request.AdditionalInformation.OrderId = "1";

            request.AdditionalInformation.AmountFood = 1;

            return BluePayClient.SaleAsync(request);
        }
```

**Comment by syunakh** [comment]
because BluePayPayments is not static class.
it is object in the test. see https://github.com/syunakh/BluePay/blob/master/BluePayPayments/BluePayPayments.Tests/BaseTests.cs#L13

**Comment by syunakh** [comment]
because BluePayClient is not static class.
it is object in the test. see https://github.com/syunakh/BluePay/blob/master/BluePayPayments/BluePayPayments.Tests/BaseTests.cs#L13

or example https://github.com/syunakh/BluePay#example

You must create this client

> var bluePayClient = new BluePayClient(accountId, secretKey, !sandbox)

and use it
